<template>
  <v-card>
    <v-card-title>
      NSM
      <v-spacer></v-spacer>
      <v-text-field
        v-model="search"
        append-icon="mdi-magnify"
        label="Search"
        single-line
        hide-details
      ></v-text-field>
    </v-card-title>
    <v-data-table
      :headers="headers"
      :items="worksheet"
      :search="search"
    ></v-data-table>
  </v-card>
</template>

<script>
export default {
  data() {
    return {
      search: "",
      headers: [
        { text: "Row Label", value: "NSM" },
        { text: "MTD Target", value: "MTD Target" },
        { text: "MTD Sales", value: "MTD Sales" },
        { text: "MTD % Ach", value: "MTD % Ach" },
        { text: "QTD Target", value: "QTD Target" },
        { text: "QTD Sales", value: "QTD Sales" },
        { text: "CP QTD CY Value", value: "CP QTD CY Value" },
        { text: "CP QTD LY Value", value: "CP QTD LY Value" },
        { text: "YTD Target", value: "YTD Target" },
        { text: "YTD Sales", value: "YTD Sales" },
        { text: "CP YTD CY Value", value: "CP YTD CY Value" },
        { text: "CP YTD LY Value", value: "CP YTD LY Value" },
      ],
      worksheet: [
        {
          NSM: "TopLeader",
          NSM_CODE: "E-1",
          TLM: "A. RAJU",
          TLM_CODE: "E-2",
          SLM: "SLM Name - BX08603    ",
          SLM_CODE: "BX08603    ",
          FLM: "FLM Name - XX50614    ",
          FLM_CODE: "XX50614    ",
          SO: "Name 171",
          DATE_MONTH: "8/1/2021",
          POS_1: "B51701    ",
          "MTD Target": 34,
          "MTD Sales": 8,
          "MTD % Ach": 0.867,
          "QTD Target": 14,
          "QTD Sales": 5,
          "CP QTD CY Value": 59,
          "CP QTD LY Value": 67,
          "YTD Target": 16,
          "YTD Sales": 103,
          "CP YTD CY Value": 12,
          "CP YTD LY Value": 129,
          MTD_LY: 136,
          MTD_CY_QTY_NRV: 2,
          MTD_LY_QTY_NRV: 12,
          QTD_LY: 84,
          QTD_CY_QTY_NRV: 149,
          YTD_LY: 1,
          QTD_LY_QTY_NRV: 68,
          YTD_TRANSIT_VALUE: 24,
          YTD_CY_QTY_NRV: 48,
          YTD_LY_QTY_NRV: 72,
          pm_pm: 192,
          DIV_PMPM: 121,
          PMPM_INCR: 98,
        },
        {
          NSM: "TopLeader",
          NSM_CODE: "E-1",
          TLM: "N RAJU",
          TLM_CODE: "E3",
          SLM: "SLM Name - BX22331    ",
          SLM_CODE: "BX22331    ",
          FLM: "FLM Name - XX27272    ",
          FLM_CODE: "XX27272    ",
          SO: "Name 257",
          DATE_MONTH: "8/1/2021",
          POS_1: "B50009    ",
          "MTD Target": 16,
          "MTD Sales": 28,
          "MTD % Ach": 0.93,
          "QTD Target": 13,
          "QTD Sales": 25,
          "CP QTD CY Value": 37,
          "CP QTD LY Value": 52,
          "YTD Target": 34,
          "YTD Sales": 132,
          "CP YTD CY Value": 190,
          "CP YTD LY Value": 72,
          MTD_LY: 190,
          MTD_CY_QTY_NRV: 136,
          MTD_LY_QTY_NRV: 36,
          QTD_LY: 121,
          QTD_CY_QTY_NRV: 186,
          YTD_LY: 82,
          QTD_LY_QTY_NRV: 184,
          YTD_TRANSIT_VALUE: 21,
          YTD_CY_QTY_NRV: 136,
          YTD_LY_QTY_NRV: 134,
          pm_pm: 81,
          DIV_PMPM: 100,
          PMPM_INCR: 118,
        },
        {
          NSM: "TopLeader",
          NSM_CODE: "E-1",
          TLM: "N SIKKA",
          TLM_CODE: "E-6",
          SLM: "SLM Name - BX16398    ",
          SLM_CODE: "BX16398    ",
          FLM: "FLM Name - XX35221    ",
          FLM_CODE: "XX35221    ",
          SO: "Name 190",
          DATE_MONTH: "8/1/2021",
          POS_1: "B61401    ",
          "MTD Target": 29,
          "MTD Sales": 8,
          "MTD % Ach": 1.025,
          "QTD Target": 45,
          "QTD Sales": 0,
          "CP QTD CY Value": 17,
          "CP QTD LY Value": 57,
          "YTD Target": 135,
          "YTD Sales": 82,
          "CP YTD CY Value": 149,
          "CP YTD LY Value": 90,
          MTD_LY: 99,
          MTD_CY_QTY_NRV: 57,
          MTD_LY_QTY_NRV: 124,
          QTD_LY: 56,
          QTD_CY_QTY_NRV: 61,
          YTD_LY: 34,
          QTD_LY_QTY_NRV: 56,
          YTD_TRANSIT_VALUE: 125,
          YTD_CY_QTY_NRV: 61,
          YTD_LY_QTY_NRV: 67,
          pm_pm: 130,
          DIV_PMPM: 100,
          PMPM_INCR: 144,
        },
        {
          NSM: "TopLeader",
          NSM_CODE: "E-1",
          TLM: "S NANDI",
          TLM_CODE: "E-77",
          SLM: "SLM Name - BX10405    ",
          SLM_CODE: "BX10405    ",
          FLM: "FLM Name - XX13886    ",
          FLM_CODE: "XX13886    ",
          SO: "Name 296",
          DATE_MONTH: "8/1/2021",
          POS_1: "B54201    ",
          "MTD Target": 24,
          "MTD Sales": 32,
          "MTD % Ach": 1.062,
          "QTD Target": 61,
          "QTD Sales": 40,
          "CP QTD CY Value": 13,
          "CP QTD LY Value": 35,
          "YTD Target": 111,
          "YTD Sales": 28,
          "CP YTD CY Value": 15,
          "CP YTD LY Value": 78,
          MTD_LY: 179,
          MTD_CY_QTY_NRV: 179,
          MTD_LY_QTY_NRV: 113,
          QTD_LY: 73,
          QTD_CY_QTY_NRV: 65,
          YTD_LY: 162,
          QTD_LY_QTY_NRV: 96,
          YTD_TRANSIT_VALUE: 140,
          YTD_CY_QTY_NRV: 35,
          YTD_LY_QTY_NRV: 52,
          pm_pm: 186,
          DIV_PMPM: 98,
          PMPM_INCR: 78,
        },
      ],
    };
  },
};
</script>
